apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: visits-service
  name: visits-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
        - image: quarkus/quarkus-petclinic-visits-service-jvm:latest
          name: vets-service
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8080
      restartPolicy: Always
