apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vets-service
  name: vets-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - image: micronaut-petclinic-vets-service
          name: vets-service
          imagePullPolicy: Never
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
          envFrom:
            - configMapRef:
                name: micronaut-petclinic-config
          ports:
            - containerPort: 8080
      restartPolicy: Always
