apiVersion: v1
kind: Service
metadata:
  labels:
    app: visits-service
  name: visits-service
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: visits-service
