apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: visits-service
  name: visits-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
        - image: spring-petclinic-cloud-visits-service
          name: visits-service
          imagePullPolicy: Never
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
          envFrom:
            - configMapRef:
                name: petclinic-config
          ports:
            - containerPort: 8080
      restartPolicy: Always
